apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
  spec:
    rules:
      - host: api.sa.homework
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                serviceName: service-backend
                servicePort: 8000
      - host: sa.homework
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                serviceName: service-frontend
                servicePort: 80
